### ISSUE TITLE
제안서 리뷰 

### ISSUE THREAD

**Issue by MisooKim2** [fusillading/C202309-P#1]
1. API 연결에 대해서는 배우지 않을 내용이라, 우려는 되지만 학생 역량으로 구현하실 수 있는 부분이라면 관계 없을 것 같습니다.
2. 말투 설정 등과 같이 다소 추상적인 내용이 포함되어 있습니다. 향후 보다 구체화하시길 바랍니다.

- 변경 사항은 제안서는 수정하지 마시고, 1차 진척보고서에 반영하여 주시길 바랍니다

**Comment by edenkim9741** [comment]
1차 진척보고서에 해당 내용 추가했습니다.
